import fs from "node:fs";
import vm from "node:vm";
import { execFileSync } from "node:child_process";

execFileSync(process.execPath, ["--check", "worker/index.js"], { stdio: "inherit" });
const html = fs.readFileSync("public/index.html", "utf8");
const scripts = [...html.matchAll(/<script(?:\s+[^>]*)?>([\s\S]*?)<\/script>/g)].map(m => m[1]).filter(Boolean);
for (let i = 0; i < scripts.length; i++) new vm.Script(scripts[i], { filename: `index-inline-${i}.js` });
if (!html.includes("telegram-commerce-bridge")) throw new Error("Telegram commerce bridge missing");
if (!html.includes("/api/payments/invoice")) throw new Error("Stars purchase flow missing");
if (!html.includes("/api/auth/telegram/callback")) throw new Error("Browser Telegram Login missing");
if (!html.includes("cross-browser-viewport-v330")) throw new Error("Cross-browser viewport fix missing");
console.log(`Inline scripts: ${scripts.length} PASS`);
if (html.includes("toDataпосилання")) throw new Error("Broken toDataURL identifier detected");
if (!html.includes("Купити +1 лист")) throw new Error("Visible Stars purchase CTA missing");
if (!html.includes("Запросити друга · отримати +1")) throw new Error("Visible referral CTA missing");
if (!html.includes("Мої покупки")) throw new Error("Visible purchases CTA missing");
if (!html.includes("/api/payments")) throw new Error("Payments history API usage missing");
if (!html.includes("Підтримка оплати")) throw new Error("Payment support CTA missing");
const worker = fs.readFileSync("worker/index.js", "utf8");
if (!worker.includes('const OWNER_TELEGRAM_ID = "375938798"')) throw new Error("Owner Telegram ID guard missing");
if (!worker.includes("/gift")) throw new Error("Owner gift command missing");
if (!worker.includes("message.from?.id")) throw new Error("Telegram sender ID handling missing");
if (!worker.includes("Розпочати Love Letter")) throw new Error("Mini App welcome button missing");
if (!worker.includes("/help")) throw new Error("Help command missing");
console.log("Love Letter Official 3.3.6 build: PASS");
